import { MediaItem } from "./media";

export type Event = {
  id: number;
  title: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
  locale: string;
  slug: string;
  start_at: string;
  end_at: string;
  description: string;
  fienta_id: any;
  intro: string;
  details: string;
  controls?: string;
  authors: string;
  thumbnail: MediaItem;
  projectLink: string;
  projects: Project[] | null;
  eventLink: string;
  eventLiveLink: string;
  eventExperimentLink: string;
  titles: string[];
  intros: string[];
  descriptions: string[];
  detailss: string[];
  contents: string[];
  status: string;
  ticketLinks: any[];
  live_content: string;
  images: MediaItem[];
  onlocation?: boolean | null;
  online?: boolean | null;
  live?: string | null;
  streamkey: string | null;
  streamUrl?: string | null;
  haslive?: boolean | null;
  radioUrl?: string | null;
  liveExternalUrl?: string | null;
  vimeoUrl: string | null;
};

interface Project {
  id: number;
  title: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
  locale: string;
  slug: string;
  pinned: boolean;
  archived: boolean;
  description: string;
  intro: string;
  authors: string;
  details: string;
  thumbnail: MediaItem;
  projectLink: string;
  titles: string[];
  intros: string[];
  descriptions: string[];
  detailss: string[];
  contents: string[];
  online?: boolean | null;
  live?: string | null;
  start_at?: string | null;
  end_at?: string | null;
  eventLiveLink: string | null;
  haslive?: boolean | null;
}
